use crate::ast::Ty;

const I: Ty = Ty::Int;
const S: Ty = Ty::Str;
const P: Ty = Ty::Ptr;

/// A known builtin: (asm target, arity, result type, param types).
/// `params` steers collection-read flavour inference when an argument
/// feeds a string/pointer parameter (e.g. `print(m.get(k))`).
pub(crate) struct Builtin {
    pub target: &'static str,
    pub arity: usize,
    pub ret: Ty,
    pub noreturn: bool,
    pub params: &'static [Ty],
}

pub(crate) fn builtin_for(path: &[String]) -> Option<Builtin> {
    let name = path.join(".");
    match name.as_str() {
        "sys.exit" | "exit" => Some(Builtin {
            target: "flint_exit",
            arity: 1,
            ret: Ty::Void,
            noreturn: true,
            params: &[I],
        }),
        "sys.write" | "write" => Some(Builtin {
            target: "flint_write",
            arity: 3,
            ret: Ty::Int,
            noreturn: false,
            params: &[I, P, I],
        }),
        "sys.read" | "read" => Some(Builtin {
            target: "flint_read",
            arity: 3,
            ret: Ty::Int,
            noreturn: false,
            params: &[I, P, I],
        }),
        "sys.open" | "open" => Some(Builtin {
            target: "flint_open",
            arity: 3,
            ret: Ty::Int,
            noreturn: false,
            params: &[S, I, I],
        }),
        "sys.close" | "close" => Some(Builtin {
            target: "flint_close",
            arity: 1,
            ret: Ty::Int,
            noreturn: false,
            params: &[I],
        }),
        "sys.brk" | "brk" => Some(Builtin {
            target: "flint_brk",
            arity: 1,
            ret: Ty::Ptr,
            noreturn: false,
            params: &[],
        }),
        "sys.socket" | "socket" => Some(Builtin {
            target: "flint_socket",
            arity: 3,
            ret: Ty::Int,
            noreturn: false,
            params: &[I, I, I],
        }),
        "sys.bind" | "bind" => Some(Builtin {
            target: "flint_bind",
            arity: 3,
            ret: Ty::Int,
            noreturn: false,
            params: &[I, P, I],
        }),
        "sys.listen" | "listen" => Some(Builtin {
            target: "flint_listen",
            arity: 2,
            ret: Ty::Int,
            noreturn: false,
            params: &[I, I],
        }),
        "sys.accept" | "accept" => Some(Builtin {
            target: "flint_accept",
            arity: 3,
            ret: Ty::Int,
            noreturn: false,
            params: &[I, P, P],
        }),
        "sys.connect" | "connect" => Some(Builtin {
            target: "flint_connect",
            arity: 3,
            ret: Ty::Int,
            noreturn: false,
            params: &[I, P, I],
        }),
        "sys.sockaddr" | "sockaddr" => Some(Builtin {
            target: "flint_sockaddr",
            arity: 5,
            ret: Ty::Ptr,
            noreturn: false,
            params: &[I, I, I, I, I],
        }),
        "sys.alloc" | "alloc" | "mem.alloc" => Some(Builtin {
            target: "flint_alloc",
            arity: 1,
            ret: Ty::Ptr,
            noreturn: false,
            params: &[I],
        }),
        "sys.free" | "free" | "mem.free" => Some(Builtin {
            target: "flint_free",
            arity: 1,
            ret: Ty::Void,
            noreturn: false,
            params: &[P],
        }),
        "memcpy" | "mem.memcpy" => Some(Builtin {
            target: "flint_memcpy",
            arity: 3,
            ret: Ty::Void,
            noreturn: false,
            params: &[P, P, I],
        }),
        "strlen" | "str.len" => Some(Builtin {
            target: "flint_strlen",
            arity: 1,
            ret: Ty::Int,
            noreturn: false,
            params: &[S],
        }),
        "print" | "io.print" => Some(Builtin {
            target: "flint_printstr",
            arity: 1,
            ret: Ty::Void,
            noreturn: false,
            params: &[S],
        }),
        "printi" | "io.printi" => Some(Builtin {
            target: "flint_printi64",
            arity: 1,
            ret: Ty::Void,
            noreturn: false,
            params: &[I],
        }),
        "atoi" | "conv.atoi" => Some(Builtin {
            target: "flint_atoi",
            arity: 1,
            ret: Ty::Int,
            noreturn: false,
            params: &[S],
        }),
        // array length (slot 0 of the array header)
        "len" => Some(Builtin {
            target: "flint_len",
            arity: 1,
            ret: Ty::Int,
            noreturn: false,
            params: &[],
        }),
        "str.cmp" | "strcmp" => Some(Builtin {
            target: "flint_strcmp",
            arity: 2,
            ret: Ty::Int,
            noreturn: false,
            params: &[S, S],
        }),
        "str.copy" | "strcpy" => Some(Builtin {
            target: "flint_strcopy",
            arity: 1,
            ret: Ty::Ptr,
            noreturn: false,
            params: &[S],
        }),
        "str.concat" | "concat" => Some(Builtin {
            target: "flint_strconcat",
            arity: 2,
            ret: Ty::Ptr,
            noreturn: false,
            params: &[S, S],
        }),
        "str.concati" | "concati" => Some(Builtin {
            target: "flint_strconcati",
            arity: 2,
            ret: Ty::Ptr,
            noreturn: false,
            params: &[S, I],
        }),
        "str.itoa" | "itoa" => Some(Builtin {
            target: "flint_itoa",
            arity: 1,
            ret: Ty::Ptr,
            noreturn: false,
            params: &[I],
        }),
        "time.millis" | "time.now" | "time" => Some(Builtin {
            target: "flint_time_millis",
            arity: 0,
            ret: Ty::Int,
            noreturn: false,
            params: &[],
        }),
        "rand.next" | "rand" => Some(Builtin {
            target: "flint_rand_next",
            arity: 0,
            ret: Ty::Int,
            noreturn: false,
            params: &[],
        }),
        "rand.range" => Some(Builtin {
            target: "flint_rand_range",
            arity: 2,
            ret: Ty::Int,
            noreturn: false,
            params: &[I, I],
        }),
        "env.get" | "getenv" => Some(Builtin {
            target: "flint_env_get",
            arity: 1,
            ret: Ty::Ptr,
            noreturn: false,
            params: &[S],
        }),
        "str.substring" => Some(Builtin {
            target: "flint_str_substring",
            arity: 3,
            ret: Ty::Ptr,
            noreturn: false,
            params: &[S, I, I],
        }),
        "str.indexOf" => Some(Builtin {
            target: "flint_str_indexof",
            arity: 2,
            ret: Ty::Int,
            noreturn: false,
            params: &[S, S],
        }),
        "str.replace" => Some(Builtin {
            target: "flint_str_replace",
            arity: 3,
            ret: Ty::Ptr,
            noreturn: false,
            params: &[S, S, S],
        }),
        "b64.encode" => Some(Builtin {
            target: "flint_b64_encode",
            arity: 1,
            ret: Ty::Ptr,
            noreturn: false,
            params: &[S],
        }),
        "b64.decode" => Some(Builtin {
            target: "flint_b64_decode",
            arity: 1,
            ret: Ty::Ptr,
            noreturn: false,
            params: &[S],
        }),
        "log.info" => Some(Builtin {
            target: "flint_log_info",
            arity: 1,
            ret: Ty::Void,
            noreturn: false,
            params: &[S],
        }),
        "log.warn" => Some(Builtin {
            target: "flint_log_warn",
            arity: 1,
            ret: Ty::Void,
            noreturn: false,
            params: &[S],
        }),
        "log.error" => Some(Builtin {
            target: "flint_log_error",
            arity: 1,
            ret: Ty::Void,
            noreturn: false,
            params: &[S],
        }),
        "log.debug" => Some(Builtin {
            target: "flint_log_debug",
            arity: 1,
            ret: Ty::Void,
            noreturn: false,
            params: &[S],
        }),
        "sys.select" => Some(Builtin {
            target: "flint_select",
            arity: 5,
            ret: Ty::Int,
            noreturn: false,
            params: &[P, I, P, P, I],
        }),
        "sys.poll" => Some(Builtin {
            target: "flint_poll",
            arity: 3,
            ret: Ty::Int,
            noreturn: false,
            params: &[P, I, I],
        }),
        "sys.epollCreate1" => Some(Builtin {
            target: "flint_epoll_create1",
            arity: 1,
            ret: Ty::Int,
            noreturn: false,
            params: &[I],
        }),
        "sys.epollCtl" => Some(Builtin {
            target: "flint_epoll_ctl",
            arity: 4,
            ret: Ty::Int,
            noreturn: false,
            params: &[I, I, P, P],
        }),
        "sys.epollWait" => Some(Builtin {
            target: "flint_epoll_wait",
            arity: 4,
            ret: Ty::Int,
            noreturn: false,
            params: &[I, P, I],
        }),
        "sys.clone" => Some(Builtin {
            target: "flint_clone",
            arity: 5,
            ret: Ty::Int,
            noreturn: false,
            params: &[P, I, I, I, I],
        }),
        "sys.futex" => Some(Builtin {
            target: "flint_futex",
            arity: 6,
            ret: Ty::Int,
            noreturn: false,
            params: &[P, I, I, I, I, I],
        }),
        // Generic syscall escape hatch: sys.syscall(num, a1, a2, a3, a4, a5).
        // The 4th syscall argument arrives in %rcx (System V call order) and
        // is moved to %r10 by the intrinsic, per the syscall ABI.
        "sys.syscall" => Some(Builtin {
            target: "flint_syscall",
            arity: 6,
            ret: Ty::Int,
            noreturn: false,
            params: &[I, I, I, I, I, I],
        }),
        // Memory mapping: mmap(addr, len, prot, flags, fd, offset) -> ptr.
        // PROT_READ|PROT_WRITE = 3; MAP_SHARED = 1, MAP_PRIVATE|MAP_ANON = 0x22.
        "sys.mmap" => Some(Builtin {
            target: "flint_mmap",
            arity: 6,
            ret: Ty::Ptr,
            noreturn: false,
            params: &[I, I, I, I, I, I],
        }),
        "sys.munmap" => Some(Builtin {
            target: "flint_munmap",
            arity: 2,
            ret: Ty::Int,
            noreturn: false,
            params: &[P, I],
        }),
        "sys.byteLoad" | "byteLoad" => Some(Builtin {
            target: "flint_byte_load",
            arity: 1,
            ret: Ty::Int,
            noreturn: false,
            params: &[P],
        }),
        "sys.byteStore" | "byteStore" => Some(Builtin {
            target: "flint_byte_store",
            arity: 2,
            ret: Ty::Void,
            noreturn: false,
            params: &[P, I],
        }),
        "sys.shortLoad" | "shortLoad" => Some(Builtin {
            target: "flint_short_load",
            arity: 1,
            ret: Ty::Int,
            noreturn: false,
            params: &[P],
        }),
        "sys.shortStore" | "shortStore" => Some(Builtin {
            target: "flint_short_store",
            arity: 2,
            ret: Ty::Void,
            noreturn: false,
            params: &[P, I],
        }),
        "sys.intLoad" | "intLoad" => Some(Builtin {
            target: "flint_int_load",
            arity: 1,
            ret: Ty::Int,
            noreturn: false,
            params: &[P],
        }),
        "sys.intStore" | "intStore" => Some(Builtin {
            target: "flint_int_store",
            arity: 2,
            ret: Ty::Void,
            noreturn: false,
            params: &[P, I],
        }),
        // Fixed-point float (Q48.16): 64-bit int, lower 16 bits = fractional.
        "math.fadd" | "fadd" => Some(Builtin {
            target: "flint_fadd",
            arity: 2,
            ret: Ty::Int,
            noreturn: false,
            params: &[I, I],
        }),
        "math.fsub" | "fsub" => Some(Builtin {
            target: "flint_fsub",
            arity: 2,
            ret: Ty::Int,
            noreturn: false,
            params: &[I, I],
        }),
        "math.fmul" | "fmul" => Some(Builtin {
            target: "flint_fmul",
            arity: 2,
            ret: Ty::Int,
            noreturn: false,
            params: &[I, I],
        }),
        "math.fdiv" | "fdiv" => Some(Builtin {
            target: "flint_fdiv",
            arity: 2,
            ret: Ty::Int,
            noreturn: false,
            params: &[I, I],
        }),
        "math.ftoi" | "ftoi" => Some(Builtin {
            target: "flint_ftoi",
            arity: 1,
            ret: Ty::Int,
            noreturn: false,
            params: &[I],
        }),
        "math.itof" | "itof" => Some(Builtin {
            target: "flint_itof",
            arity: 1,
            ret: Ty::Int,
            noreturn: false,
            params: &[I],
        }),
        "math.fcmp" | "fcmp" => Some(Builtin {
            target: "flint_fcmp",
            arity: 2,
            ret: Ty::Int,
            noreturn: false,
            params: &[I, I],
        }),
        // Thread and synchronization builtins.
        "sys.threadCreate" => Some(Builtin {
            target: "flint_thread_create",
            arity: 2,
            ret: Ty::Int,
            noreturn: false,
            params: &[I, I],
        }),
        "sys.threadJoin" => Some(Builtin {
            target: "flint_thread_join",
            arity: 1,
            ret: Ty::Int,
            noreturn: false,
            params: &[I],
        }),
        "sys.mutexLock" => Some(Builtin {
            target: "flint_mutex_lock",
            arity: 1,
            ret: Ty::Void,
            noreturn: false,
            params: &[P],
        }),
        "sys.mutexUnlock" => Some(Builtin {
            target: "flint_mutex_unlock",
            arity: 1,
            ret: Ty::Void,
            noreturn: false,
            params: &[P],
        }),
        "sys.atomicCas" => Some(Builtin {
            target: "flint_atomic_cas",
            arity: 3,
            ret: Ty::Int,
            noreturn: false,
            params: &[P, I, I],
        }),
        "sys.nanosleep" => Some(Builtin {
            target: "flint_nanosleep",
            arity: 2,
            ret: Ty::Int,
            noreturn: false,
            params: &[P, I],
        }),
        // JSON key-value extraction.
        "json.get" => Some(Builtin {
            target: "flint_json_get",
            arity: 2,
            ret: Ty::Ptr,
            noreturn: false,
            params: &[S, S],
        }),
        "json.geti" => Some(Builtin {
            target: "flint_json_geti",
            arity: 2,
            ret: Ty::Int,
            noreturn: false,
            params: &[S, S],
        }),
        // Varargs-style string formatting: str.format(fmt, a, b, c, d) -> *byte
        // Supports %d (int), %s (*byte), %b (int as bool) placeholders.
        "str.format" => Some(Builtin {
            target: "flint_str_format",
            arity: 5,
            ret: Ty::Ptr,
            noreturn: false,
            params: &[S, I, I, I, I],
        }),
        _ => None,
    }
}
